### PR TITLE
Create softiesAtHeart section for softies no longer in SE.

### PR DESCRIPTION
**Pull request by AndrewMcBurney**
If we decide we don't want these changes, I'm :100:% fine with keeping it the way it is.

Thoughts?

### Changes

screen shot 2018-02-07 at 5 57 17 pm

screen shot 2018-02-07 at 5 57 00 pm

### CODE REVIEW

**Comment by AndrewMcBurney** [comment]
Should we have a class discussion on this PR? lol

**Comment by lpan** [comment]
@icechen1

**Comment by davepagurek** [comment]
@itsbilal is there a more tasteful way to do this? I mean, the truth is... they're not in SE any more. And I think they should stay on the site, but just having them under the heading of SE 2019 is kind of objectively false

**Comment by itsbilal** [comment]
Serious response: I don't think we should be bragging about our record breaking attrition rate on a page that's literally meant to show off our class. I see this page as a cohort page, not as any form of authoritative source of who's still in our class/program or not. If anyone really cares, they can stalk us on FB/WatIAm, etc.

At the very least I think we should get more input from our class before we make any change like this (and in the process of getting that input, we'd also be indirectly reminding them to put their own profiles on there - only a small minority of the class is represented on that page currently. I'm not on it either 😂 ). Right now this change would lead to a page that's almost 50% ex-SE, and that looks weird no matter how you slice it.

**Comment by AndrewMcBurney** [comment]
Okay, I'm going to close the PR now, but let's discuss if we'd like to reopen it / further thoughts via chat.

**Pull request closed without merging**
