### PR TITLE
remove CS manz

### PR DESCRIPTION
**Pull request by lpan**
:cry:

### CODE REVIEW

**Comment by AndrewMcBurney** [comment]
:'(

**Comment by davepagurek** [comment]
I think we should add a section at the bottom for ex-SE ("SE at heart" or something). Maybe a flag in the json or something.

**Comment by lpan** [comment]
image

Request to change him back to SE

**Comment by pobeng** [comment]
@lpan can you write an integration to directly modify Quest data from softi.es? 

@itsbilal might be able to help if you're stuck.

**Pull request closed without merging**
